# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/BGPS/Desktop/Tesis/Tutoriales/xdc - zybo/Zybo-Master.xdc

# IP: ip/bram_instrucciones/bram_instrucciones.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_instrucciones || ORIG_REF_NAME==bram_instrucciones} -quiet] -quiet
